[package]
name = "fwcloud-agent"
version = "1.0.0"
license = "GNU AFFERO GENERAL PUBLIC LICENSE"
description = "FWCloud Agent for firewalls management"
readme = "README.md"
homepage = "https://fwcloud.net"
repository = "https://github.com/soltecsis/fwcloud-agent"
authors = ["Carles Munyoz <cmunyoz@soltecsis.com>"]
keywords = ["fwcloud", "fwcloud-agent", "firewall", "firewall cloud", "iptables", "nftables", "openvpn"]
edition = "2018"

[package.metadata.deb] 
maintainer = "Carles Munyoz <cmunyoz@soltecsis.com>"
copyright = "SOLTECSIS, SL"
extended-description = """\
FWCloud Agent daemon for simplify and improve \
firewalls management from a FWCloud console."""
depends = "openssl"
section = "utility"
priority = "optional"
assets = [
    ["target/release/fwcloud-agent", "opt/fwcloud/agent/", "700"],
    [".env.example", "opt/fwcloud/agent/.env", "600"],
    ["pkg/fwcloud-agent.service", "lib/systemd/system/", "644"],
    ["pkg/fwcloud-agent.conf", "etc/rsyslog.d/", "644"],
    ["pkg/fwcloud-agent", "etc/logrotate.d/", "644"],
    ["pkg/fwcloud-agent.1", "usr/share/man/man1/", "644"],
]
maintainer-scripts = "pkg/maintainer-scripts"

[package.metadata.rpm]
package = "fwcloud-agent"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
fwcloud-agent = { path = "/usr/bin/fwcloud-agent" }

[dependencies]
thiserror = "1.0.28"
dotenv = "0.15.0"
validator = { version = "0.14.0", features = ["derive"] }
serde = "1.0.129"
serde_json = "1.0.67"
lazy_static = "1.4.0"
actix-web = { version = "3", features = ["openssl"] }
openssl = { version = "0.10", features = ["v110"] }
actix-service = "1.0.6"
actix-multipart = "0.3.0"
actix-web-requestid = "1.1.0"
rand = "0.8.4"
regex = "1.5.4"
log = "0.4.0"
env_logger = "0.9.0"
num_cpus = "1.13.0"
sanitize-filename = "0.3.0"
futures = "0.3.1"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
tracing = "0.1.26"
tracing-subscriber = "0.3.1"
thread-id = "4.0.0"
subprocess = "0.2.7"
sha2 = "0.9.8"
hex = "0.4.3"
chrono = "0.4.19"

[dev-dependencies]
actix-rt = "2.2.0"
mockall = "0.10.2"
mockall_derive = "0.10.2"
