[package]
name = "fwcloud-agent"
version = "0.1.0"
edition = "2018"
authors = ["Carles Munyoz <cmunyoz@soltecsis.com>"]
license = "GNU AFFERO GENERAL PUBLIC LICENSE"
description = "FWCloud Agent for firewalls management"
keywords = ["fwcloud", "fwcloud-agent"]
repository = "https://github.com/soltecsis/fwcloud-agent"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
validator = { version = "0.14.0", features = ["derive"] }
serde = "1.0.129"
serde_json = "1.0.67"
lazy_static = "1.4.0"
actix-web = "3"
actix-multipart = "0.3.0"
actix-web-requestid = "1.1.0"
rand = "0.8.4"
regex = "1.5.4"
log = "0.4.0"
env_logger = "0.9.0"
num_cpus = "1.13.0"
sanitize-filename = "0.3.0"
futures = "0.3.1"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
thiserror = "1.0.28"

[dev-dependencies]
actix-rt = "2.2.0"