#!/bin/sh
set -e

ROOT_DIR="/opt/fwcloud/agent"

DIR_LIST="${ROOT_DIR}/etc ${ROOT_DIR}/tmp ${ROOT_DIR}/data ${ROOT_DIR}/log"
for DIR in $DIR_LIST; do
  mkdir "$DIR"
  chmod 700 "$DIR"
done

# Generate self-signed certificate.
cd "${ROOT_DIR}/etc"
openssl req -x509 -newkey rsa:4096 -nodes -keyout key.pem -out cert.pem -days 36500 -subj '/CN=fwcloud-agent' > /dev/null 2>&1
chmod 600 key.pem cert.pem

# Generate API KEY
KEY=`openssl rand -base64 48|sed 's/[[:punct:]]/x/g'`
sed -i -E "s|API_KEY=\"([a-zA-Z0-9[:punct:]]){64}\"|API_KEY=\"$KEY\"|" /opt/fwcloud/agent/.env

# Enable and start FWCloud-Agent daemon.
systemctl enable fwcloud-agent
systemctl start fwcloud-agent
#systemctl status fwcloud-agent

#DEBHELPER#

exit 0

