#!/bin/sh
set -e

systemctl stop fwcloud-agent

ROOT_DIR="/opt/fwcloud/agent"
DIR_LIST="${ROOT_DIR}/etc ${ROOT_DIR}/tmp ${ROOT_DIR}/data ${ROOT_DIR}/log"
for DIR in $DIR_LIST; do
  if [ -d "$DIR" -a ! -z "$(ls -A ${DIR})" ]; then
    rm "${DIR}/*"
  fi
done

#DEBHELPER#

exit 0
