#!/bin/sh
set -e

#echo "PARAMETERS: $0 $1 $2 $3 $4 $5"

ROOT_DIR="/opt/fwcloud/agent"
chmod 700 "$ROOT_DIR"

DIR_LIST="${ROOT_DIR}/etc ${ROOT_DIR}/tmp ${ROOT_DIR}/data ${ROOT_DIR}/log"
for DIR in $DIR_LIST; do
  if [ ! -d "$DIR" ]; then
    mkdir "$DIR"
  fi
  chmod 700 "$DIR"
done

# Generate self-signed certificate.
if [ ! -f "${ROOT_DIR}/etc/key.pem" -a ! -f "${ROOT_DIR}/etc/cert.pem" ]; then
  cd "${ROOT_DIR}/etc"
  openssl req -x509 -newkey rsa:4096 -nodes -keyout key.pem -out cert.pem -days 36500 -subj '/CN=fwcloud-agent' > /dev/null 2>&1
  chmod 600 key.pem cert.pem
fi

# Generate API KEY
if [ -f "${ROOT_DIR}/.env.upgrade" ]; then
  mv -f "${ROOT_DIR}/.env.upgrade" "${ROOT_DIR}/.env"
else
  KEY=`openssl rand -base64 48|sed 's/[[:punct:]]/x/g'`
  sed -i -E "s|API_KEY=\"([a-zA-Z0-9[:punct:]]){64}\"|API_KEY=\"$KEY\"|" "${ROOT_DIR}/.env"
fi

# Enable and start FWCloud-Agent daemon.
systemctl enable fwcloud-agent
systemctl start fwcloud-agent
#systemctl status fwcloud-agent

#DEBHELPER#

exit 0

