#!/bin/sh
set -e

ROOT_DIR="/opt/fwcloud/agent"
chmod 700 "$ROOT_DIR"

DIR_LIST="${ROOT_DIR}/etc ${ROOT_DIR}/tmp ${ROOT_DIR}/data ${ROOT_DIR}/log"
for DIR in $DIR_LIST; do
  mkdir "$DIR"
  chmod 700 "$DIR"
done

UPGRADE_DIR="${ROOT_DIR}/.upgrade"
if [ -d "${UPGRADE_DIR}" ]; then
  # Restore the files that we want to preserve after the upgrade.
  ITEMS_LIST=".env etc data log"
  for ITEM in $ITEMS_LIST; do
    cp -pr "${UPGRADE_DIR}/${ITEM}" "${ROOT_DIR}"
  done

  rm -rf "${UPGRADE_DIR}"
else
  # Generate self-signed certificate.
  cd "${ROOT_DIR}/etc"
  openssl req -x509 -newkey rsa:4096 -nodes -keyout key.pem -out cert.pem -days 36500 -subj '/CN=fwcloud-agent' > /dev/null 2>&1
  chmod 600 key.pem cert.pem

  # Generate API KEY
  KEY=`openssl rand -base64 48|sed 's/[[:punct:]]/x/g'`
  sed -i -E "s|API_KEY=\"([a-zA-Z0-9[:punct:]]){64}\"|API_KEY=\"$KEY\"|" /opt/fwcloud/agent/.env
fi

# Enable and start FWCloud-Agent daemon.
systemctl enable fwcloud-agent
systemctl start fwcloud-agent
#systemctl status fwcloud-agent

#DEBHELPER#

exit 0

