#!/bin/sh
set -e

systemctl stop fwcloud-agent

ROOT_DIR="/opt/fwcloud/agent"
DIR_LIST="${ROOT_DIR}/etc ${ROOT_DIR}/tmp ${ROOT_DIR}/data ${ROOT_DIR}/log"
for DIR in $DIR_LIST; do
  if [ -d "$DIR" ]; then
    FL=`ls $DIR`
    for F in $FL; do
      rm "${DIR}/${F}" 
    done
  fi
done

#DEBHELPER#

exit 0
