//! Same-authority address changes. Preparation never changes CrowdSec files.
use super::*;
use crate::crowdsec::{
    bouncers,
    command::CrowdSecCommand,
    errors::{TRANSITION_CONFLICT, TRANSITION_FAILED, TRANSITION_RECOVERY_REQUIRED},
};
use serde::{Deserialize, Serialize};
use std::{
    io::Write,
    os::unix::fs::{OpenOptionsExt, PermissionsExt},
    path::{Path, PathBuf},
    time::Duration,
};
use tokio::{fs, process::Command, time::timeout};
use uuid::Uuid;

const CONFIG: &str = "/etc/crowdsec/config.yaml";
const CREDENTIALS: &str = "/etc/crowdsec/local_api_credentials.yaml";
const ENGINE: &str = "crowdsec.service";
const BOUNCER: &str = "crowdsec-firewall-bouncer.service";

#[derive(Deserialize, Serialize)]
pub struct AddressTransition {
    pub kind: TransitionKind,
    pub transition_id: Uuid,
    pub phase: TransitionPhase,
    pub expected: TransitionTarget,
    pub target: TransitionTarget,
    pub backend: Option<CrowdSecFirewallBackend>,
    pub changed: bool,
}

// Kept only in a mode-0600 recovery file; never returned or logged.
#[derive(Deserialize, Serialize)]
struct Backup {
    credentials: String,
    bouncer: Option<String>,
    engine_running: bool,
    bouncer_running: bool,
}

fn failed() -> FwcError {
    FwcError::crowdsec(
        TRANSITION_FAILED,
        "CrowdSec Local API address change failed",
    )
}
fn conflict() -> FwcError {
    FwcError::crowdsec(
        TRANSITION_CONFLICT,
        "CrowdSec transition conflicts with current configuration or transition state",
    )
}
fn recovery() -> FwcError {
    FwcError::crowdsec(
        TRANSITION_RECOVERY_REQUIRED,
        "CrowdSec address transition requires recovery before further changes",
    )
}
fn directory(data: &str) -> PathBuf {
    Path::new(data).join("crowdsec/transitions")
}
fn state_path(data: &str, id: Uuid) -> PathBuf {
    directory(data).join(format!("{id}.json"))
}
fn backup_path(data: &str, id: Uuid) -> PathBuf {
    directory(data).join(format!("{id}.backup"))
}

fn atomic_write(path: &Path, contents: &[u8]) -> Result<()> {
    let temp = path.with_extension(format!("{}.tmp", Uuid::new_v4()));
    let result = (|| {
        let mut file = std::fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .mode(0o600)
            .open(&temp)?;
        file.write_all(contents)?;
        file.sync_all()?;
        std::fs::rename(&temp, path)?;
        std::fs::File::open(path.parent().ok_or_else(failed)?)?.sync_all()?;
        Ok(())
    })();
    if result.is_err() {
        let _ = std::fs::remove_file(&temp);
    }
    result.map_err(|_: FwcError| failed())
}

fn save(data: &str, state: &AddressTransition) -> Result<()> {
    atomic_write(
        &state_path(data, state.transition_id),
        &serde_json::to_vec(state).map_err(|_| failed())?,
    )
}

pub async fn load(data: &str, id: Uuid) -> Result<AddressTransition> {
    let bytes = fs::read(state_path(data, id))
        .await
        .map_err(|_| conflict())?;
    serde_json::from_slice(&bytes).map_err(|_| recovery())
}

/// Prepared plans do not reserve the node: activate rechecks the effective source.
/// An interrupted activation must be recovered before another mutation.
pub async fn ensure_idle(data: &str) -> Result<()> {
    let mut entries = match fs::read_dir(directory(data)).await {
        Ok(entries) => entries,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(()),
        Err(_) => return Err(recovery()),
    };
    while let Some(entry) = entries.next_entry().await.map_err(|_| recovery())? {
        if entry.path().extension().and_then(|x| x.to_str()) != Some("json") {
            continue;
        }
        let state: serde_json::Value =
            serde_json::from_slice(&fs::read(entry.path()).await.map_err(|_| recovery())?)
                .map_err(|_| recovery())?;
        let phase: TransitionPhase = serde_json::from_value(
            state.get("phase").cloned().ok_or_else(recovery)?,
        )
        .map_err(|_| recovery())?;
        if matches!(
            phase,
            TransitionPhase::Activating
                | TransitionPhase::Preparing
                | TransitionPhase::AwaitingValidation
                | TransitionPhase::RecoveryRequired
                | TransitionPhase::ActivePendingFinalize
        ) {
            return Err(recovery());
        }
    }
    Ok(())
}

/// Conservative reader for block mappings generated by CrowdSec/FWCloud.
/// Ambiguous, duplicate or complex YAML values are rejected before mutation.
fn scalar(contents: &str, key: &str) -> Result<String> {
    let mut values = contents
        .lines()
        .filter_map(|line| line.strip_prefix(&format!("{key}:")));
    let raw = values.next().ok_or_else(conflict)?.trim();
    if values.next().is_some() {
        return Err(conflict());
    }
    let raw = raw.split(" #").next().unwrap_or(raw).trim();
    let value = raw.trim_matches('"').trim_matches('\'');
    if value.is_empty()
        || value.chars().any(char::is_whitespace)
        || value.starts_with(['&', '*', '|', '>', '{', '['])
    {
        return Err(conflict());
    }
    Ok(value.to_string())
}

fn replace_url(contents: &str, key: &str, url: &str) -> Result<String> {
    scalar(contents, key)?;
    let mut result = String::new();
    for line in contents.split_inclusive('\n') {
        if line.starts_with(&format!("{key}:")) {
            result.push_str(&format!("{key}: {url}"));
            if line.ends_with('\n') {
                result.push('\n');
            }
        } else {
            result.push_str(line);
        }
    }
    Ok(result)
}

fn same_url(a: &str, b: &str) -> Result<bool> {
    Ok(lapi::remote_lapi_url(a)? == lapi::remote_lapi_url(b)?)
}

async fn running(service: &str) -> Result<bool> {
    let output = timeout(
        Duration::from_secs(15),
        Command::new("/usr/bin/systemctl")
            .args(["is-active", service])
            .output(),
    )
    .await
    .map_err(|_| failed())?
    .map_err(|_| failed())?;
    match String::from_utf8_lossy(&output.stdout).trim() {
        "active" => Ok(true),
        "inactive" | "failed" | "unknown" => Ok(false),
        _ => Err(conflict()),
    }
}
async fn service(action: &str, name: &str) -> Result<()> {
    let output = timeout(
        Duration::from_secs(60),
        Command::new("/usr/bin/systemctl")
            .args([action, name])
            .output(),
    )
    .await
    .map_err(|_| failed())?
    .map_err(|_| failed())?;
    if output.status.success() {
        Ok(())
    } else {
        Err(failed())
    }
}

async fn inspect(
    expected: &TransitionTarget,
    backend: Option<CrowdSecFirewallBackend>,
) -> Result<Backup> {
    // Fail closed on unsupported layouts or override files.
    if Path::new("/etc/crowdsec/config.yaml.local").exists()
        || Path::new("/etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml.local").exists()
    {
        return Err(conflict());
    }
    let config = fs::read_to_string(CONFIG).await.map_err(|_| conflict())?;
    let mut path = Vec::<String>::new();
    let mut disabled = false;
    let mut credentials_path = false;
    for line in config
        .lines()
        .filter(|l| !l.trim().is_empty() && !l.trim_start().starts_with('#'))
    {
        let indent = line.len() - line.trim_start().len();
        if indent % 2 != 0 {
            return Err(conflict());
        }
        let level = indent / 2;
        path.truncate(level);
        if let Some((key, value)) = line.trim().split_once(':') {
            if path == ["api", "server"] && key == "enable" {
                disabled = value.trim() == "false";
            }
            if path == ["api", "client"] && key == "credentials_path" {
                credentials_path = value.trim().trim_matches('"').trim_matches('\'') == CREDENTIALS;
            }
            path.push(key.to_string());
        }
    }
    if !disabled || !credentials_path {
        return Err(conflict());
    }
    let credentials = fs::read_to_string(CREDENTIALS)
        .await
        .map_err(|_| conflict())?;
    if Some(scalar(&credentials, "login")?) != expected.machine_name
        || !same_url(
            &scalar(&credentials, "url")?,
            expected.lapi_url.as_deref().ok_or_else(conflict)?,
        )?
    {
        return Err(conflict());
    }
    scalar(&credentials, "password")?;
    let bouncer = match fs::read_to_string(bouncers::BOUNCER_CONFIG_PATH).await {
        Ok(contents) => Some(contents),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => None,
        Err(_) => return Err(conflict()),
    };
    if expected.local_remediation {
        let contents = bouncer.as_deref().ok_or_else(conflict)?;
        if !bouncers::configuration_is_fwcloud_managed(contents)
            || !bouncers::configuration_is_set_only(contents, backend.ok_or_else(conflict)?)
            || !same_url(
                &scalar(contents, "api_url")?,
                expected.lapi_url.as_deref().ok_or_else(conflict)?,
            )?
        {
            return Err(conflict());
        }
        scalar(contents, "api_key")?;
    } else if bouncer.is_some() {
        return Err(conflict());
    }
    Ok(Backup {
        credentials,
        bouncer,
        engine_running: running(ENGINE).await?,
        bouncer_running: if expected.local_remediation {
            running(BOUNCER).await?
        } else {
            false
        },
    })
}

pub async fn prepare(
    data: &str,
    request: &TransitionPrepareRequest,
    progress: &CrowdSecProgress,
) -> Result<AddressTransition> {
    validate(request)?;
    if request.authority_changed
        || request.expected.mode != TransitionMode::Machine
        || request.target.mode != TransitionMode::Machine
        || request.expected.local_remediation != request.target.local_remediation
    {
        return Err(unsupported());
    }
    if state_path(data, request.transition_id).exists() {
        let state = load(data, request.transition_id).await?;
        if state.expected != request.expected
            || state.target != request.target
            || state.backend != request.backend
        {
            return Err(conflict());
        }
        return Ok(state);
    }
    ensure_idle(data).await?;
    inspect(&request.expected, request.backend).await?;
    let changed = !same_url(
        request.expected.lapi_url.as_deref().ok_or_else(conflict)?,
        request.target.lapi_url.as_deref().ok_or_else(conflict)?,
    )?;
    if changed {
        preflight(request, progress).await?;
    }
    std::fs::create_dir_all(directory(data)).map_err(|_| failed())?;
    std::fs::set_permissions(directory(data), std::fs::Permissions::from_mode(0o700))
        .map_err(|_| failed())?;
    let state = AddressTransition {
        kind: TransitionKind::Address,
        transition_id: request.transition_id,
        phase: if changed {
            TransitionPhase::Prepared
        } else {
            TransitionPhase::Completed
        },
        expected: request.expected.clone(),
        target: request.target.clone(),
        backend: request.backend,
        changed,
    };
    save(data, &state)?;
    progress.typed_message(
        CrowdSecProgressMessageType::Success,
        if changed {
            "CrowdSec address change prepared; configuration is unchanged"
        } else {
            "CrowdSec Local API address is unchanged"
        },
    );
    Ok(state)
}

async fn restore(backup: &Backup) -> Result<()> {
    service("stop", ENGINE).await?;
    if backup.bouncer.is_some() {
        service("stop", BOUNCER).await?;
    }
    atomic_write(Path::new(CREDENTIALS), backup.credentials.as_bytes())?;
    if let Some(contents) = &backup.bouncer {
        atomic_write(
            Path::new(bouncers::BOUNCER_CONFIG_PATH),
            contents.as_bytes(),
        )?;
    }
    if backup.engine_running {
        CrowdSecCommand::cscli(&["lapi", "status"])?
            .execute()
            .await?;
        service("start", ENGINE).await?;
    }
    if backup.bouncer_running {
        service("start", BOUNCER).await?;
    }
    Ok(())
}

pub async fn recover(data: &str, id: Uuid) -> Result<AddressTransition> {
    let mut state = load(data, id).await?;
    if state.phase == TransitionPhase::RolledBack {
        return Ok(state);
    }
    if !matches!(
        state.phase,
        TransitionPhase::Activating | TransitionPhase::RecoveryRequired
    ) {
        return Err(conflict());
    }
    let backup: Backup = serde_json::from_slice(
        &fs::read(backup_path(data, id))
            .await
            .map_err(|_| recovery())?,
    )
    .map_err(|_| recovery())?;
    if restore(&backup).await.is_err() {
        let _ = service("stop", ENGINE).await;
        if backup.bouncer.is_some() {
            let _ = service("stop", BOUNCER).await;
        }
        state.phase = TransitionPhase::RecoveryRequired;
        save(data, &state)?;
        return Err(recovery());
    }
    state.phase = TransitionPhase::RolledBack;
    save(data, &state)?;
    fs::remove_file(backup_path(data, id))
        .await
        .map_err(|_| failed())?;
    Ok(state)
}

pub async fn activate(
    data: &str,
    request: &TransitionActivateRequest,
    progress: &CrowdSecProgress,
) -> Result<AddressTransition> {
    if request.bouncer_api_key.is_some() {
        return Err(invalid(
            "An address-only change preserves the existing Bouncer key",
        ));
    }
    let mut state = load(data, request.transition_id).await?;
    if matches!(
        state.phase,
        TransitionPhase::Completed | TransitionPhase::ActivePendingFinalize
    ) {
        return Ok(state);
    }
    if state.phase != TransitionPhase::Prepared {
        return Err(conflict());
    }
    ensure_idle(data).await?;
    let backup = inspect(&state.expected, state.backend).await?;
    let url = lapi::remote_lapi_url(state.target.lapi_url.as_deref().ok_or_else(conflict)?)?;
    lapi::ensure_remote_lapi_reachable(&url).await?;
    atomic_write(
        &backup_path(data, state.transition_id),
        &serde_json::to_vec(&backup).map_err(|_| failed())?,
    )?;
    state.phase = TransitionPhase::Activating;
    save(data, &state)?;
    progress.typed_message(
        CrowdSecProgressMessageType::Info,
        "Updating CrowdSec Local API address while preserving credentials",
    );
    let result: Result<()> = async {
        service("stop", ENGINE).await?;
        if backup.bouncer.is_some() {
            service("stop", BOUNCER).await?;
        }
        atomic_write(
            Path::new(CREDENTIALS),
            replace_url(&backup.credentials, "url", url.as_str())?.as_bytes(),
        )?;
        if let Some(contents) = &backup.bouncer {
            atomic_write(
                Path::new(bouncers::BOUNCER_CONFIG_PATH),
                replace_url(contents, "api_url", url.as_str())?.as_bytes(),
            )?;
        }
        CrowdSecCommand::cscli(&["lapi", "status"])?
            .execute()
            .await?;
        service("start", ENGINE).await?;
        if !running(ENGINE).await? {
            return Err(failed());
        }
        if backup.bouncer.is_some() {
            service("start", BOUNCER).await?;
            if !running(BOUNCER).await? {
                return Err(failed());
            }
        }
        Ok(())
    }
    .await;
    if result.is_err() {
        progress.typed_message(
            CrowdSecProgressMessageType::Error,
            "CrowdSec address update failed; restoring original configuration",
        );
        recover(data, state.transition_id).await?;
        return Err(failed());
    }
    state.phase = TransitionPhase::ActivePendingFinalize;
    save(data, &state)?;
    progress.typed_message(
        CrowdSecProgressMessageType::Success,
        "CrowdSec Local API address updated; awaiting topology confirmation",
    );
    Ok(state)
}

pub async fn finalize(data: &str, id: Uuid) -> Result<AddressTransition> {
    let mut state = load(data, id).await?;
    if !matches!(
        state.phase,
        TransitionPhase::ActivePendingFinalize | TransitionPhase::Completed
    ) {
        return Err(conflict());
    }
    match fs::remove_file(backup_path(data, id)).await {
        Ok(()) => (),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => (),
        Err(_) => return Err(failed()),
    }
    state.phase = TransitionPhase::Completed;
    save(data, &state)?;
    Ok(state)
}

#[cfg(test)]
mod tests {
    use super::*;
    #[tokio::test]
    async fn persists_safe_state_and_blocks_interrupted_or_unfinalized_changes() {
        let root = std::env::temp_dir().join(format!("fwcloud-transition-test-{}", Uuid::new_v4()));
        let data = root.to_str().unwrap();
        std::fs::create_dir_all(directory(data)).unwrap();
        let id = Uuid::new_v4();
        let target = TransitionTarget {
            mode: TransitionMode::Machine,
            machine_name: Some("fwcloud-node".to_string()),
            lapi_url: Some("http://192.0.2.1:8080/".to_string()),
            local_remediation: false,
        };
        let mut state = AddressTransition {
            kind: TransitionKind::Address,
            transition_id: id,
            phase: TransitionPhase::Prepared,
            expected: target.clone(),
            target,
            backend: None,
            changed: true,
        };
        save(data, &state).unwrap();
        assert!(ensure_idle(data).await.is_ok());
        assert_eq!(
            std::fs::metadata(state_path(data, id))
                .unwrap()
                .permissions()
                .mode()
                & 0o777,
            0o600
        );
        state.phase = TransitionPhase::Activating;
        save(data, &state).unwrap();
        assert!(ensure_idle(data).await.is_err());
        assert_eq!(
            load(data, id).await.unwrap().phase,
            TransitionPhase::Activating
        );
        state.phase = TransitionPhase::AwaitingValidation;
        save(data, &state).unwrap();
        assert!(ensure_idle(data).await.is_err());
        state.phase = TransitionPhase::ActivePendingFinalize;
        save(data, &state).unwrap();
        assert!(ensure_idle(data).await.is_err());
        let backup = Backup {
            credentials: "password: secret".into(),
            bouncer: None,
            engine_running: true,
            bouncer_running: false,
        };
        atomic_write(
            &backup_path(data, id),
            &serde_json::to_vec(&backup).unwrap(),
        )
        .unwrap();
        assert!(!serde_json::to_string(&state).unwrap().contains("secret"));
        finalize(data, id).await.unwrap();
        assert!(!backup_path(data, id).exists());
        assert!(ensure_idle(data).await.is_ok());
        assert_eq!(
            finalize(data, id).await.unwrap().phase,
            TransitionPhase::Completed
        );
        std::fs::remove_dir_all(root).unwrap();
    }
    #[test]
    fn changes_only_url_preserving_credentials_and_comments() {
        let input =
            "# machine\nurl: 'http://192.0.2.1:8080/'\nlogin: fwcloud-node\npassword: \"secret\"\n";
        let output = replace_url(input, "url", "http://192.0.2.2:8080/").unwrap();
        assert_eq!(
            output,
            "# machine\nurl: http://192.0.2.2:8080/\nlogin: fwcloud-node\npassword: \"secret\"\n"
        );
    }
    #[test]
    fn changes_bouncer_url_without_touching_key_or_sets() {
        let input = "api_url: http://192.0.2.1:8080/\napi_key: secret\nblacklists_ipv4: crowdsec-blacklists\n";
        assert_eq!(
            replace_url(input, "api_url", "http://192.0.2.2:8080/").unwrap(),
            input.replacen("192.0.2.1", "192.0.2.2", 1)
        );
    }
    #[test]
    fn rejects_ambiguous_or_missing_urls_and_normalizes_trailing_slash() {
        assert!(replace_url("url: x\nurl: y\n", "url", "z").is_err());
        assert!(replace_url("login: node\n", "url", "z").is_err());
        assert!(same_url("http://192.0.2.1:8080", "http://192.0.2.1:8080/").unwrap());
    }
}
