name: FWCloud-Agent CI

on:
  push:
    branches: [main, devel]

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.rustversion.outputs.rustversion }}
    steps:
    - uses: actions/checkout@v2
    - run: cargo check
    - run: cargo pkgid
    - run: 'echo "$(cargo pkgid | cut -d# -f2)"'
    - id: rustversion
      run: 'echo "::set-output name=rustversion::$(cargo pkgid | cut -d# -f2)"'

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -D warnings

  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: '--ignore-tests'

  build:
    needs: checks
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build

  ubuntu-amd64:
    needs: [build]
    runs-on: ubuntu-latest
    name: Ubuntu amd64
    steps:
    - uses: actions/checkout@v2
    - name: Build DEB package
      id: ubuntu
      uses: ebbflow-io/cargo-deb-amd64-ubuntu@1.0
    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: ubuntu-amd64
        path: ./target/x86_64-unknown-linux-musl/debian/*

  fedora-amd64:
    needs: [build]
    runs-on: ubuntu-latest
    name: Fedora amd64
    steps:
    - uses: actions/checkout@v2
    - name: Install required packages
      run: sudo apt install -y cargo rpm libssl-dev pkg-config
    - name: Install cargo-rpm
      run: cargo install cargo-rpm
    - name: Build RPM package
      run: cargo rpm build
    - name: Upload RPM Artifact
      uses: actions/upload-artifact@v2
      with:
        name: fedora-amd64
        path: ./target/release/rpmbuild/RPMS/x86_64/*

  # raspbian-armv7:
  #   needs: [build]
  #   runs-on: ubuntu-latest
  #   name: Raspbian armv7
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Build package
  #     id: debbuild
  #     uses: ebbflow-io/cargo-deb-armv7-debian@1.0
  #   - name: Upload package
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: raspbian
  #       path: ./target/armv7-unknown-linux-musleabihf/debian/*

  upload:
    needs: [ubuntu-amd64, fedora-amd64]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    name: Deploy
    steps:
    - uses: actions/checkout@v2
    - name: Download packages
      uses: actions/download-artifact@v2
    - name: List packages
      run: ls -lha 
    - name: Upload Ubuntu amd64 package
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: pkg.fwcloud.net
        username: fwcloud-pkg
        password: ${{ secrets.FWCLOUD_PKG_FTP_PASSWORD }}
        local-dir: ./ubuntu-amd64/
        server-dir: ./fwcloud-agent/deb/
    - name: Upload Fedora amd64 package
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: pkg.fwcloud.net
        username: fwcloud-pkg
        password: ${{ secrets.FWCLOUD_PKG_FTP_PASSWORD }}
        local-dir: ./fedora-amd64/
        server-dir: ./fwcloud-agent/rpm/