name: FWCloud-Agent CI

on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]

jobs:
  quickcheck:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.rustversion.outputs.rustversion }}
    steps:
    - uses: actions/checkout@v2
    - run: cargo check
    - run: cargo pkgid
    - run: 'echo "$(cargo pkgid | cut -d# -f2)"'
    - id: rustversion
      run: 'echo "::set-output name=rustversion::$(cargo pkgid | cut -d# -f2)"'
  
  build:
    needs: quickcheck
    name: 'build-${{matrix.os}}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test

  debbuild:
    needs: [build]
    runs-on: ubuntu-latest
    name: Amd64Deb
    steps:
    - uses: actions/checkout@v2
    - name: BuildDeb
      id: debbuild
      uses: ebbflow-io/cargo-deb-amd64-ubuntu@1.0
    - name: Upload Deb Artifact
      uses: actions/upload-artifact@v2
      with:
        name: amd64deb
        path: ./target/x86_64-unknown-linux-musl/debian/*

  upload:
    needs: [debbuild]
    runs-on: ubuntu-latest
    name: Deploy
    - name: Download packages
      uses: actions/download-artifact@v2
      run: ls -lha
    - name: Upload packages
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: pkg.fwcloud.net
        username: fwcloud-pkg
        password: ${{ secrets.FWCLOUD_PKG_FTP_PASSWORD }}
        local-dir: ./
        server-dir: ./