name: FWCloud-Agent CI

on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]

jobs:
  quickcheck:
    name: Quick checks
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.rustversion.outputs.rustversion }}
    steps:
    - uses: actions/checkout@v2
    - run: cargo check
    - run: cargo pkgid
    - run: 'echo "$(cargo pkgid | cut -d# -f2)"'
    - id: rustversion
      run: 'echo "::set-output name=rustversion::$(cargo pkgid | cut -d# -f2)"'
  
  build:
    needs: quickcheck
    name: 'build-${{matrix.os}}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test

  debian-amd64:
    needs: [build]
    runs-on: ubuntu-latest
    name: Debian amd64
    steps:
    - uses: actions/checkout@v2
    - name: Build package
      id: debian
      uses: ebbflow-io/cargo-deb-amd64-ubuntu@1.0
    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: debian
        path: ./target/x86_64-unknown-linux-musl/debian/*

  raspbian-armv7:
    needs: [build]
    runs-on: ubuntu-latest
    name: Raspbian armv7
    steps:
    - uses: actions/checkout@v2
    - name: Build package
      id: debbuild
      uses: ebbflow-io/cargo-deb-armv7-debian@1.0
    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: raspbian
        path: ./target/armv7-unknown-linux-musleabihf/debian/*

  upload:
    needs: [debian-amd64, raspbian-armv7]
    runs-on: ubuntu-latest
    name: Deploy
    steps:
    - uses: actions/checkout@v2
    - name: Download packages
      uses: actions/download-artifact@v2
    - name: List packages
      run: ls -lha 
    - name: Upload packages
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: pkg.fwcloud.net
        username: fwcloud-pkg
        password: ${{ secrets.FWCLOUD_PKG_FTP_PASSWORD }}
        local-dir: ./debian/amd64/
        server-dir: ./fwcloud-agent/debian/amd64/